### ISSUE TITLE
simplegrid在ie10 11下存在的问题。

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon.oniui#440]
最近在项目中使用simplegrid的时候，发现simplegrid.js里面。
vm._tbodyRenderedCallback 中avalon(table).innerHeight()获取的高度在ie11,ie10下。跟实际的高度始终有差距。造成页面展示不完全。
暂时只能通过修改其中seTimeout(delay,100)中的时间足够大来保证正确性。因为这个时间因很多因素决定，可大可小。个人觉得这不是一个可行的解决方式，是否可以尽快修复。
我在OniUI也发现同样的原因。

**Comment by RubyLouvre** [comment]
无解，因为要生成节点 这需要花时间
