### ISSUE TITLE
datepicker组件onClose返回参数有误

### ISSUE THREAD

**Issue by scott-wong** [RubyLouvre/avalon.oniui#454]
http://ued.qunar.com/oniui/datepicker/avalon.datepicker.ex7.html
选择“2015-1-11”，返回的是“2015-2-11”。
测试浏览器：ie各版本、Chrome39。

另外最新版还有另外一个问题，当选择某个日期后也触发onClose时，onClose返回的是之前的日期，不是选择后的日期。

**Comment by shirlyLoveU** [comment]
第一个问题： 选择2015-01-11之后返回的是2015-01-11
第二个问题： 只要日历框关闭都会触发onClose回调，如果不需要你可以不配置onClose回调

**Comment by scott-wong** [comment]
sorry,我没说清楚，http://ued.qunar.com/oniui/datepicker/avalon.datepicker.ex7.html，在这个页面的onClose回调那里选择一个日期，在onClose回调的第一个参数参数返回的日期月份不对，比如选择“2015-01-11”，可以看到控制台输出的是“Wed Feb 11 2015 00:00:00 GMT+0800 (中国标准时间)”。

第二个问题，只要日历框关闭都会触发onClose回调没有问题，问题是点击选择日期后触发的onClose回调的第一个参数不是点击后的日期，而是点击之前的日期。

**Comment by shirlyLoveU** [comment]
done
