### ISSUE TITLE
pager在alwaysShow的时候，当前为第1页或最后一页的时仍然可点击触发onJump

### ISSUE THREAD

**Issue by lwbjing** [RubyLouvre/avalon.oniui#456]
建议阻止掉。
avalon.pager.js
line 74 
<pre>
case "next":
    vm.currentPage++
    // 当前为第一页时阻止事件
    if (vm.currentPage &gt;= vm.totalPages) {
        vm.currentPage = vm.totalPages
        return false
    }
    break
case "prev":
    vm.currentPage--
    // 当前为最后一页时阻止事件
    if (vm.currentPage &lt;= 1) {
        vm.currentPage = 1
        return false
    }
    break
</pre>

**Comment by RubyLouvre** [comment]
已修
