### ISSUE TITLE
validation组件，使用data-duplex-event="change"，延迟到失去焦点才验证。 bug

### ISSUE THREAD

**Issue by niuliwei** [RubyLouvre/avalon.oniui#467]
validation组件，使用data-duplex-event="change"，延迟到失去焦点才验证。 bug。
在线例子：http://ued.qunar.com/oniui/index.html#avalon.validation.doc.html?example=ex2

输入第一个字符的时候就会触发验证规则。

**Comment by RubyLouvre** [comment]
已经修好
