### ISSUE TITLE
oniui的demo里的 dropdownlist 例子有问题

### ISSUE THREAD

**Issue by zhangchunlin** [RubyLouvre/avalon.oniui#495]
在chrome和ie8下测试是一样的

表现为下拉的那些项有时候会出现有的时候不出现,一开始不会出现,需要点击一下搜索框才会显示出来,如果有显示的话,点击一下其他区域,然后就又不见了

**Comment by RubyLouvre** [comment]
条件不足无法判定啊

**Comment by zhangchunlin** [comment]
正美你是说无法重现还是怎么着?

**Comment by RubyLouvre** [comment]
是的

**Comment by zhangchunlin** [comment]
奇怪了,我这里ie8/chrome/firefox全测过了都能重现阿,下拉的那些 name * 都是有时候出现有时候不出现

**Comment by zhangchunlin** [comment]
Q群:"【神族】青岛-scgy 2015-1-29 9:39:21
我的dropdown跟你说的表现一样"

**Comment by shirlyLoveU** [comment]
你是在hotelued的demo'里出现的还是本地，最好描述下复现步骤

**Comment by zhangchunlin** [comment]
@shirlyLoveU 
-访问 http://ued.qunar.com/oniui/index.html
-点击 dropdownlist
-然后再点击下面的 "dropdownlist demo"
-点击dropdownlist 例子里的dropdownlist
-此时是没有下拉选项那些 name 1 name 2什么的,是空的
-点击下拉里的搜索框,下拉选项就马上显示出来了
-此时再点击一次dropdownlist,下拉收起,再点击一次dropdownlist,下拉展开,此时还是有 name 1 name 2的
-把鼠标在外面点击一下让焦点不在dropdown,然后再点击一次dropdownlist,此时展开的选项下又是空的,没有name 1 name 2这些

**Comment by shirlyLoveU** [comment]
逻辑本来就是这样的，点击搜索框才展示数据，点击其他的地方隐藏搜索框

**Comment by zhangchunlin** [comment]
@shirlyLoveU 要是demo故意做成这样那还好
不过一般用的时候应该是不搜索的时候也有下拉的,因为有可能不搜索就能选到想要的项

**Comment by zhangchunlin** [comment]
@shirlyLoveU 貌似demo已经改了哈?

**Comment by zhangchunlin** [comment]
本地验证也通过了,谢谢!
