### ISSUE TITLE
请教如何在项目中使用avalon.oniui的组件

### ISSUE THREAD

**Issue by rubylab** [RubyLouvre/avalon.oniui#511]
在项目中使用oniui的一些组件，需要克隆git@github.com:RubyLouvre/avalon.oniui.git整个项目然后放到静态资源中吗？遇到问题：使用simplergrid只引用相关的highlight、loading和pager scrollbar等目录下的css和js，前台无法正常grid，请教该如何解决，谢谢。
![js-tree2](https://cloud.githubusercontent.com/assets/4611267/6058022/658e3a58-ad5e-11e4-9f8c-d94dc2e3bcdb.png)
![js-tree2](https://cloud.githubusercontent.com/assets/4611267/6058046/90912c7e-ad5e-11e4-9763-df935ea956d3.png)

**Comment by RubyLouvre** [comment]
simplegrid不是许多例子吗, 运行一下它们

**Comment by rubylab** [comment]
谢谢 ！克隆到项目中，然后删除所有的.html文件是这样使用吗   build-tree.sh 是怎么使用的 ./build-tree.sh 执行后没有输出

**Comment by RubyLouvre** [comment]
build-tree.sh 是什么啊

**Comment by rubylab** [comment]
是  [avalon.oniui]( https://github.com/RubyLouvre/avalon.oniui ) 目录下的脚本
