### ISSUE TITLE
avalon.dropdownlist 使用起来会有 404 not found

### ISSUE THREAD

**Issue by zhangchunlin** [RubyLouvre/avalon.oniui#513]
比如 demo 就有: http://ued.qunar.com/oniui/index.html#avalon.dropdownlist.doc.html

 Failed to load resource: the server responded with a status of 404 (Not Found)
http://ued.qunar.com/oniui/dropdownlist/avalon.dropdownlist.css.map Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by RubyLouvre** [comment]
http://ued.qunar.com/oniui/dropdownlist/avalon.dropdownlist.css.map 是位于注释中,不会影响你的代码
