### ISSUE TITLE
dropdownlist如何取到选择的值?

### ISSUE THREAD

**Issue by zhangchunlin** [RubyLouvre/avalon.oniui#516]
```
<div ms-widget="dropdownlist,actrl,ddopts" ms-duplex="mdmodel"></div> {{mdmodel}}
```
这样貌似无效取不到值阿

**Comment by shirlyLoveU** [comment]
通过avalon.vmodels.actrl.searchItem来获取，不需要设置duplex

**Comment by zhangchunlin** [comment]
这部分文档例子都木有,建议加一下
另外如果我需要监听这个值的变化以便做一些处理怎么办呢? 还是要用 duplex 来 watch 吧?

**Comment by RubyLouvre** [comment]
我们可以通过dropdownVm.value得到当前选中项的value值,
也可以通过dropdownVm.getSelected()得到当前选中项的value值
此外，我们也可能通过dropdownVm.activeIndex得到当前选中项的对应的索引值
