### ISSUE TITLE
Datepicker 的BUG

### ISSUE THREAD

**Issue by wolfgangmay** [RubyLouvre/avalon.oniui#526]
不同计算机，换了浏览器DatePicker 渲染都有问题啊 ，无论是官方DEMO的网页还是我自己的项目都有这问题。
![b1](https://cloud.githubusercontent.com/assets/9377895/6203514/1c9e09e4-b561-11e4-936d-ed42032ed2bb.PNG)
![b2](https://cloud.githubusercontent.com/assets/9377895/6203515/1ceac770-b561-11e4-9283-7bc57e1cb74e.PNG)

**Comment by wolfgangmay** [comment]
建议 : 是否可以去掉或者加一个开关控制 节假日（春节，元宵节）的显示。

**Comment by xuzicn** [comment]
不知道你的操作系统，浏览器版本的状况如何？我测了一下chrome40, FF, IE6和11没有发现渲染的问题。

**Comment by wolfgangmay** [comment]
你好，
我是在13天之前发现这个BUG的（今天是27号），12天之前提出，你们的项目组在11天之前修复了这个BUG。  你可以查看DatePicker的更新记录和这个Issues的发布时间。


祝你们的这个项目越来越好。









在 2015-02-27 11:13:44，"徐子龙" <notifications@github.com> 写道：


不知道你的操作系统，浏览器版本的状况如何？我测了一下chrome40, FF, IE6和11没有发现渲染的问题。
