### ISSUE TITLE
mmState: 建议在 transitionTo a from a 时做优化

### ISSUE THREAD

**Issue by ascoders** [RubyLouvre/avalon.oniui#540]
## 引言
很久很久以前，分页使用ajax做的，每个a标签写上笨笨的javascript:void(0)再加上藏匿于脚本中的监听。

如今可以交给avalon的跳转了，a标签可以优雅的写上 #!/article/123?from=10&number=10

## 问题
问题随之而来，如今mmState对所有跳转都一视同仁，显然对分页来说，点击按钮后仅仅是更新了数据，再同步。可是console显示的是拗口的transitionTo a from a，然后执行了onChange+onAfterload（大部分人都在onAfterload做了初始化工作吧，包括编辑器等等，这着实挺影响性能的）。

鉴于同state之间跳转需要每次重新初始化的情况极少，应该可以作为特殊情况看待。

## 建议
判断页面跳转时，如果当前state与目的state相同，只触发onChange，不触发onAfterload（甚至找模版之类的步骤都跳过，仅仅执行onChange）。为了兼容出一个硬刷新参数等等。

**Comment by gogoyqj** [comment]
新版里面，增加了一个ignoreChange配置，可以用来屏蔽，视图刷新，但是会进入onEnter逻辑
