### ISSUE TITLE
使用ms-include-src后如何让页面重新加载,而不是从TemplateCache中再次获取?

### ISSUE THREAD

**Issue by 178220709** [RubyLouvre/avalon.oniui#543]
引入了mmRouter 和mmHistory 做spa
我有个页面输出当前时间,第一次访问输出 :2015/3/8 1:17:28.
然后后续再次访问,任然是2015/3/8 1:17:28..
有些实时页面,我希望是每次都能重新加载.
该怎么做啊?

**Comment by RubyLouvre** [comment]
手动从TemplateCache删掉

**Comment by 178220709** [comment]
靠，是我自己想歪了。
我还是没能脱离传统mvc的路子，我的时间是用razor引擎写c#（服务端）代码打印的，
spa加载的view，应该就是一个非常单纯的view，而这个时间，其实已经是model的范畴了。
2015/3/8 1:17:28. 这个数据，应该来自于ViewModel，由它提供，而不是内置在View中。
