### ISSUE TITLE
关于validation，我要添加业务相关的check怎么办？

### ISSUE THREAD

**Issue by msiibola** [RubyLouvre/avalon.oniui#545]
我现在是加的validationHooks，但是有个问题，我客户端的check会同时进行,就是下面的代码，maxlength,minlength,int,和自己写的test方法，会全部都执行，我希望能够在manlength,minlength，int这些check  OK的情况下，在执行test。这个该怎么办呢？
```
ms-duplex-test-maxlength-minlength-int=""
validation: {
						validationHooks:{
							test:{
								message: "已经存在",
								get: function(value, data, next){
									var isOK;
									$.ajax({
										type: 'POST',
										dataType: 'json',
										contentType:'application/json;charset=UTF-8',
										url: 'check',
										data: {username: createUser.username},
										async:false,
										success: function(result) {
											isOK = result;
										},
										error:function() {
											isOK = false;
										}
									});
									next(isOK)
									return value
								}
							}
						},
```

**Comment by RubyLouvre** [comment]
ms-duplex-maxlength-minlength-int-test

**Comment by msiibola** [comment]
不对，加到后面一样的。
而且message的显示顺序是根据   ms-duplex-maxlength-minlength-int-test 的顺序来的。
越写后面越优先，这样会先出现test的消息，然后是int的错误消息。

**Comment by msiibola** [comment]
还有一个小问题，下拉框select项目 怎么实现他 change 就check 啊？ 
加data-duplex-event="change"  好像没起作用。

**Comment by RubyLouvre** [comment]
我晚上看看

**Comment by msiibola** [comment]
随便再请问一下，
文件里面写的，
<p> 也可以在页面添加不依赖于ms-duplex的绑定</p>
 ```javascript
 validateVM.data.push({
 valueAccessor: function(){}
 validateParam: "xxx",
 element: element
 })

请问这种不依赖ms-duplex的方式  怎么个写法啊？

**Comment by dragonwong** [comment]
@msiibola 

* 目前不支持 select change 后自动 check，但是会在 blur 后自动 check。如果非要实现这个功能，可以绑定 `data-duplex-changed`，然后在回调中手动触发该 select 的 validate。

```html
<select ms-duplex-required="a" placholder="不能为空" data-duplex-changed="ww">
    <option value=""></option>
    <option value="1">1</option>
    <option value="2">2</option>
</select>
```

```javascript
var testVm = avalon.define({
    $id: 'test',
    a: ''
    ww: function() {
        testVm.validate(testVm.data[0]);
    }
})
```

* 不依赖于 ms-duplex 的绑定，你可以在控制台输出 `validateVM.data` 参考下。这个方法的应用场景应该很少吧。

**Comment by msiibola** [comment]
@dragonwong 
那请一下，你知道这个业务相关check的怎么处理么？
我就是想长度啊整型啊这些checkOK的时候，再执行后台相关的check。
现在好像是都要执行的。

**Comment by RubyLouvre** [comment]
```
 validationHooks:{
                            test:{
                                message: "已经存在",
                                get: function(value, data, next){
                                    var isOK;
                                    $.ajax({
                                        type: 'POST',
                                        dataType: 'json',
                                        contentType:'application/json;charset=UTF-8',
                                        url: 'check',
                                        data: {username: createUser.username},
                                        async:false,
                                        success: function(result) {
                                             next(true)
                                        },
                                        error:function() {
                                            next(false)
                                        }
                                    });
                                  
                                    return value
                                }
                            }
                        },

```

**Comment by msiibola** [comment]
@RubyLouvre  
你这么写不是一样的会走后台么？
而且后台返回false一样的走success。这样永远是没有错误的。。
error 只有通信失败，出现异常的时候才走的。

我是希望在有其他validate错误的时候 不走到后台去。
不执行
$.ajax({
                                        type: 'POST',
                                        dataType: 'json',
                                        contentType:'application/json;charset=UTF-8',
                                        url: 'check',
                                        data: {username: createUser.username},
                                        async:false,
                                        success: function(result) {
                                             next(true)
                                        },
                                        error:function() {
                                            next(false)
                                        }
                                    });
有什么属性能让我在$,ajax前面加个判断条件么？ 就是是否有错误这么一个条件。

还有个问题。
ms-duplex-maxlength-minlength-int-test
这样写法，是从左到右check顺序，但是显示错误消息的时候，是取得lastPromise，最后出错的一个消息。

**Comment by msiibola** [comment]
我改的  avalon.validation.js 解决了。

            vm.validate = function(data, isValidateAll, event) {
                var value = data.valueAccessor()
                var inwardHooks = vmodel.validationHooks
                var globalHooks = avalon.duplexHooks
                var promises = []
                var elem = data.element
                var err = []  // 我添加的语句
                data.validateParam.replace(/\w+/g, function(name) {
                    var hook =  globalHooks[name]
                    if (hook == undefined) {                      // 我添加的语句
                        if (err.length == 0) {                        // 我添加的语句
                            hook = inwardHooks[name]        // 我添加的语句
                        } else {                                           // 我添加的语句
                            return;                                       // 我添加的语句
                        }                                                    // 我添加的语句
                    }                                                        // 我添加的语句
                    if (!elem.disabled) {
                        var resolve, reject
                        promises.push(new Promise(function(a, b) {
                            resolve = a
                            reject = b
                        }))
                        var next = function(a) {
                            if (data.norequired)
                                a = true
                            delete data.norequired
                            if (a) {
                                resolve(true)
                            } else {
                                var reason = {
                                    element: elem,
                                    data: data.data,
                                    message: elem.getAttribute("data-duplex-message") || hook.message,
                                    validateRule: name,
                                    getMessage: getMessage
                                }
                                err.push(reason);               // 我添加的语句
                                resolve(reason)
                            }
                        }
                        data.data = {}
                        hook.get(value, data, next)
                    }
                })
