### ISSUE TITLE
时间控件有点小问题

### ISSUE THREAD

**Issue by msiibola** [RubyLouvre/avalon.oniui#547]
当两个时间控件上下并排的时候，第二个时间控件浮动在日期选择框上面的。
![qq 20150311181113](https://cloud.githubusercontent.com/assets/11239115/6594197/0db0ee1c-c81a-11e4-800e-9077465ba293.png)

**Comment by RubyLouvre** [comment]
注明什么浏览器及版本，你是怎么操作的

**Comment by msiibola** [comment]
IE11，Chrome，QQ浏览器，都是这个效果。
我就是放了两个时间控件。

<div class="control-group">
									<label class="control-label">时间1</label>
									<div class="controls">
										<input  id="deadline" ms-controller="deadline" ms-widget="datepicker" data-datepicker-change-month-and-year="true" data-datepicker-start-day="0" ms-duplex="date" data-datepicker-timer="true"/>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">时间2</label>
									<div class="controls">
										<input  id="investAvlDate" ms-controller="investAvlDate" ms-widget="datepicker" data-datepicker-change-month-and-year="true" data-datepicker-start-day="0" ms-duplex="date" data-datepicker-timer="true"/>
									</div>
								</div>

**Comment by niuliwei** [comment]
z-index: 1; avalon.datepicker.css 样式问题去掉就可以了

**Comment by msiibola** [comment]
@niuliwei 
谢谢，已经解决了。
