### ISSUE TITLE
datepicker demo(带有时间选择)

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon.oniui#567]
官网链接地址：http://hotelued.qunar.com/oniui/datepicker/avalon.datepicker.ex11.html
测试环境：谷歌
看console上面有时候会加载http://hotelued.qunar.com/oniui/slider/avalon.slider.html.js错误的js文件。导致页面加载不出来

**Comment by RubyLouvre** [comment]
升级一下avalon就好了,这是加载器的BUG

**Comment by davidduwei** [comment]
更新后,ie8 存在 
执行[callback450]模块的factory抛错： Error: Failed
SCRIPT16389: Failed
文件: avalon.js，行: 2256，列: 9

**Comment by RubyLouvre** [comment]
callback450  应该为你的一个用户模块，查一下哪个文件错了

**Comment by davidduwei** [comment]
avalon恢复到之前版本就好了。
 ie8定位到 avalon.js，行: 2256，列: 9 var nextNode = node.nextSibling  nextNode 为未定义

**Comment by RubyLouvre** [comment]
我让同事看看

**Comment by RubyLouvre** [comment]
已经修复 parseHTML BUG
