### ISSUE TITLE
tooltip 有没有简单一点的示例，或者详细一点的说明。。。

### ISSUE THREAD

**Issue by cos800** [RubyLouvre/avalon.oniui#570]
比如 `vm.$qqOpt` 是什么东西，是必须的吗，一定要这个名称吗？
`contentGetter` 又是什么……
`ms-widget="tooltip,ppo, $qqOpt"`
这里的ppo又是什么。。。

**Comment by xuzicn** [comment]
ppo是vm的id，以后你可以通过avalon.vmodels.ppo来访问到这个vm；$qqOpt是vm的配置项的名称。

**Comment by RubyLouvre** [comment]
看这里，你连基础语法都不会 http://avalonjs.github.io/#zh/bindings/widget.html

**Comment by cos800** [comment]
widget 确实是还没有用过，直接就去使用 oniui 了。
那我先了解一下 widget 吧，谢谢了。
