### ISSUE TITLE
validation如何验证“2-4位中文”类似这样的多重条件

### ISSUE THREAD

**Issue by cos800** [RubyLouvre/avalon.oniui#571]
我只知道：
ms-duplex-chs 验证输入必须是中文，
ms-duplex-minlength 验证输入最少位数
ms-duplex-maxlength 验证输入最多位数

如果是多个条件的话，必须自定义验证规则吗？

**Comment by RubyLouvre** [comment]
ms-duplex-chs-minlength-maxlength

**Comment by cos800** [comment]
原来 还可以这样。。。话说oniui文档。。。（省略五百字）。。。
加油！
