### ISSUE TITLE
pager组件prev按钮在消失时不触发onJump

### ISSUE THREAD

**Issue by malcolmyu** [RubyLouvre/avalon.oniui#613]
复现方式，见 [pager ex2](http://ued.qunar.com/oniui/pager/avalon.pager.ex2.html)，先点击第7页，之后点击prev按钮，页面hash不变，即 `onJump` 回调没有触发。

查源码发现在触发 `onJump` 回调时节点需无 `state-disabled` 样式，见 [源码](https://github.com/RubyLouvre/avalon.oniui/blob/master/pager/avalon.pager.js#L94)；而当prev按钮消失时又会被加上 `state-disabled` 样式，见 [源码](https://github.com/RubyLouvre/avalon.oniui/blob/master/pager/avalon.pager.html#L3) 。故有此 bug。

**Comment by RubyLouvre** [comment]
已修
