### ISSUE TITLE
fileuploader 组件，上传文件的名字可以文件的名称么？一直是“blob”

### ISSUE THREAD

**Issue by niuliwei** [RubyLouvre/avalon.oniui#617]
![qq 20150505173808](https://cloud.githubusercontent.com/assets/344041/7470244/c0a5811e-f34d-11e4-97bf-f902d0eb3b31.png)

**Comment by niuliwei** [comment]
哪里可以配置么?谢谢

**Comment by xuzicn** [comment]
可以。
				vm.$uploaderOptions1 = $$.mix({
					requiredParamsConfig: {
						blobParamName: "data",
						fileTokenParamName: "fileIndicator",
						totalChunkParamName: "chunkAmount",
						chunkIndexParamName: "chunkIndex",
						fileNameParamName: "name"
					}
				}, basicOptions);

requiredParamsConfig可以指定所有的必备的参数名。

**Comment by niuliwei** [comment]
![qq 20150506100603](https://cloud.githubusercontent.com/assets/344041/7486410/a40b0a08-f3d7-11e4-98ee-3162594259ad.png)

**Comment by xuzicn** [comment]
filename已经传回后，为何需要再提供一遍文件名呢？

**Comment by niuliwei** [comment]
好，谢谢
