### ISSUE TITLE
smartgrid 

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon.oniui#618]
ie8 smartgrid 提示 vmodel.loadingVModel提示为空或不是对象

**Comment by davidduwei** [comment]
更新了相关的组件。
ie8下smartgrid仅仅第一次强制刷新浏览器可用，通过链接访问的会存在avalon.vmodels.smartgridGoodCatalog.pager.perPages为空此类问题。

**Comment by RubyLouvre** [comment]
写一个简单的页面
