### ISSUE TITLE
关于tab 组件 下动态创建 div 使用  ms-include-src 加载一个模块 avalon 抛出异常但是正常运行 

### ISSUE THREAD

**Issue by 493409332** [RubyLouvre/avalon.oniui#624]
warning: pager-NavigationsimplegridVM 已经存在于avalon.vmodels中
主要代码
 avalon.vmodels.tabVM.add({
                            title: data.leaf.name,
                            name: data.leaf.guid,
                            content: '<div  ms-include-src="page.' + data.leaf.guid + '">模板加载未成功</div>'
  });

model.js
avalon.templateCache.navigationindextext = navigationtext;
avalon.define("Navigation", function (vm)
{
........
}

 avalon.vmodels.Index.page.Navigationindex = "navigationindextext";

选项卡关闭一次后 再打开该页能正常运行但是有异常提示 本人有强迫症 求司徒大大拯救    
 
个人怀疑 tab 关闭后 资源释放不完全

**Comment by RubyLouvre** [comment]
到runjs写例子
