### ISSUE TITLE
oniui 推荐对代码进行合并打包吗？如果有，那么打包的方案是什么

### ISSUE THREAD

**Issue by WeweTom** [RubyLouvre/avalon.oniui#625]
使用 avalon 自带的 loader 或使用第三方的 loader 都有一个问题：若代码拆分的比较散，所以到生产环境前需要进行合并打包。 

那么目前来看， 如何解决代码合并的问题，通过打包？大家的方案是怎样的？

**Comment by gogoyqj** [comment]
oniu直接可以用r.js打包

**Comment by WeweTom** [comment]
css 和 text 也能打在一起？

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/tree/master/combo 这里提供了各种材料了

**Comment by WeweTom** [comment]
哦，不错不错

**Comment by bzksx2** [comment]
请问是如何进行打包配置的呢？麻烦给个样例吧

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/qapp2/issues/1
