### ISSUE TITLE
问一个问题，oniui的Layout，倒是能分区了，但是如何将其他dom元素添加到对应的分区中去呢？

### ISSUE THREAD

**Issue by kuafuwang** [RubyLouvre/avalon.oniui#638]
问一个问题，oniui的Layout，倒是能分区了，但是如何将其他dom元素添加到对应的分区中去呢？

**Comment by kuafuwang** [comment]
我在例子中看到了添加方法了。

<div ms-layout-dock="north">
                        北区配置尺寸为{{northRegion.size}}。
                    </div>
                    <div ms-layout-dock="west">
                        西区配置尺寸为{{westRegion.size}}。
                    </div>
                    <div ms-layout-dock="east">
                        东区配置尺寸为{{eastRegion.size}}。
                    </div>
                    <div ms-layout-dock="centre">
                        直接改变Layout的大小时，各区域会按照百分比配置重新计算。但是经过拖放改变区域尺寸后，该区域配置的百分比失效并被实际尺寸覆盖。
                    </div>

**Comment by xuzicn** [comment]
几种方式都可以解决这个问题
1.可以使用ms-include引入模板。
2.dock的dom节点内的内容不会被删除，也不做任何修改，所以可以采用 <div ms-layout-dock="west"><img src=".." alt="" /></div>。这样一个图片是dock在左边的。
