### ISSUE TITLE
加载avalon.uploader.html时会变成加载avalon.uploader.html.js，导致404报错

### ISSUE THREAD

**Issue by ProMonkey** [RubyLouvre/avalon.oniui#643]
![image](https://cloud.githubusercontent.com/assets/5961216/8018995/a24cfaa4-0c6a-11e5-9e6d-dbf5dde4b6e3.png)

**Comment by xuzicn** [comment]
浏览器版本？组件版本？
另外uploader是一个实验性质的组件，如果可能的话，请选用FileUploader

**Comment by ProMonkey** [comment]
chrome 版本 43.0.2357.65 m 不会报这个错，但是360急速浏览器（chrome内核版本号：30.0.1599.101）会报这个错， 组件版本1.2，另外只要把avalon.uploader.html再avalon.uploader.js前加载进来就可以正常使用。
