### ISSUE TITLE
uploader 组件问题 

### ISSUE THREAD

**Issue by MaxMooc** [RubyLouvre/avalon.oniui#645]
Dear 正美：

ms-if="el.type=='Image'" ms-widget="uploader,$,$opts" 

ms-widget不能和ms-if同时在div标签上出现，负责绑定不上，把   ms-if="el.type=='Image'"  去掉uploader就正常，因为swf创建的obj是在head上的avalonHide标签里面，咋解决？

**Comment by RubyLouvre** [comment]
外包一个DIV,DIV上面加ms-if

**Comment by MaxMooc** [comment]
外包div，也是不行，我之前试过的

**Comment by zjkyz8** [comment]
外包DIV也是不行的，ms-if会把当前元素和其子元素都生成两份，其中一份放到header里，而upload控件在插入flash object时会调用GetElementById, 这个API总是会返回插入到Header里的元素，从而导致该控件无法正常工作

**Comment by RubyLouvre** [comment]
现在改用fileuploader吧
