### ISSUE TITLE
如果配置了require的baseUrl，组件内的相对路径就不正确了

### ISSUE THREAD

**Issue by zzbcoder** [RubyLouvre/avalon.oniui#648]
![image](https://cloud.githubusercontent.com/assets/2271825/8102195/ae675188-1050-11e5-94e2-b30de4415ba5.png)

![image](https://cloud.githubusercontent.com/assets/2271825/8102106/022b1b20-1050-11e5-8426-c3af58fa7b98.png)

```js
 <script src="vendor/avalon/avalon.js" data-main="modules/main.js"></script>

require.config({
	baseUrl: "modules",
        path:{
           "avalon.mmState":  "../vendor/avalon/mmRouter/mmState",
       }
})
require("avalon.mmState")
```
require("avalon.mmState") 就会加载失败，因为mmPromise路径已经错了，有什么好的解决方案吗？

**Comment by gogoyqj** [comment]
requirejs？mmState.js和mmRequest.js的代码有点小问题，去掉 define的第一个参数，有指定module name，requirejs就不能正常了

**Comment by zzbcoder** [comment]
是用的avalon内置的require.
![image](https://cloud.githubusercontent.com/assets/2271825/8102686/86eb34fe-1054-11e5-9dba-9b96a0e2fd02.png)

**Comment by gogoyqj** [comment]
你这文件存在么

**Comment by zzbcoder** [comment]
文件存在的。
你看第一张图，正确路径为 "vendor/avalon/mmPromise/mmPromise".

**Comment by RubyLouvre** [comment]
更新最新的mmPromise
