### ISSUE TITLE
为什么在IEtest下 layout这个组件会提示错误呢

### ISSUE THREAD

**Issue by kuafuwang** [RubyLouvre/avalon.oniui#655]
![qq 20150617163516](https://cloud.githubusercontent.com/assets/3636678/8202719/29b0e9fe-150f-11e5-91ba-c189968b8f63.png)

**Comment by kuafuwang** [comment]
我发现把代码注释中带有//@这样字眼的注释去掉就没有问题了。

**Comment by RubyLouvre** [comment]
IDE的问题,换一个
