### ISSUE TITLE
为什么在IETest下spinner这个组件会提示错误呢

### ISSUE THREAD

**Issue by kuafuwang** [RubyLouvre/avalon.oniui#656]
![2](https://cloud.githubusercontent.com/assets/3636678/8202765/7679857a-150f-11e5-8036-848baaa8ec19.png)

**Comment by kuafuwang** [comment]
我发现把代码中涉及到//@config 如果希望选框水平排列则设置vertical为false，默认垂直排列 的注释去掉就好了。

**Comment by kuafuwang** [comment]
我发现把代码注释中带有//@这样字眼的注释去掉就没有问题了。

**Comment by RubyLouvre** [comment]
你 的IDE问题

**Comment by kuafuwang** [comment]
不是，我是在IETest下，用IE8实例来跑的时候，报的错误。

**Comment by kuafuwang** [comment]
我只是用IDE来展示出错的行号
