### ISSUE TITLE
mmState对页面渲染时没有对容器添加指定的avalonctrl属性

### ISSUE THREAD

**Issue by peterPan-1989** [RubyLouvre/avalon.oniui#657]
mmState对页面渲染时没有对容器添加指定的avalonctrl属性,如
![image](https://cloud.githubusercontent.com/assets/6194604/8205455/72005866-1523-11e5-9aa8-dd2815afb566.png)
在页面无法找到该容器的avalonctrl属性。导致无法在该controller中向下分发事件

**Comment by gogoyqj** [comment]
这倒是和之前的事件传播机制不兼容，如果你实在需要使用，那么就不要通过$ctrl.$vmodels来指定vm，还是在模板里写ms-controller吧

**Comment by peterPan-1989** [comment]
ok～～只能通过ms-controller
