### ISSUE TITLE
IE7，8下面smartgrid组件报错

### ISSUE THREAD

**Issue by lkiarest** [RubyLouvre/avalon.oniui#670]
现在的实现是在首页上有一个导航条，然后点击某个菜单会使用body里的标签：
```
<div ms-include-src="page"></div>
```
指定不同的page来加载不同的页面。
假如导航可以进入一个页面A，和一个页面B，页面B中定义了一个smartgrid，
在第一次打开B的时候没有问题，但是之后切换到A页面之后再切换回B页面，IE8就会报错：
```
SCRIPT438: 对象不支持此属性或方法
文件: avalon.smartgrid.js，行: 592，列: 21
```
请问是我的用法问题吗？ 谢谢！

**Comment by RubyLouvre** [comment]
那必须的 http://www.cnblogs.com/rubylouvre/p/4012709.html

**Comment by lkiarest** [comment]
hi， @RubyLouvre 你好 ~ 报错的这行代码是说_allSelected这个属性未定义，不过这个是在smartgrid里面实现的。我只是使用这个组件，请问需要在外部传这个参数进去吗 ？

**Comment by RubyLouvre** [comment]
那不知道了
作者休假去了

**Comment by lkiarest** [comment]
额。。 知道啥时候回来不~  我们项目准备用这个框架的，想先写个原型调研下

**Comment by lkiarest** [comment]
不过刚才我在smartgrid里加上这个定义就不报错了，先这样吧~~
```
line 293: vm._allSelected = false;
```

**Comment by RubyLouvre** [comment]
我建议不要使用grid,我们内部是很少使用grid, grid很容易出现性能问题

**Comment by lkiarest** [comment]
@RubyLouvre  你好，请问有grid的替代方案吗。。不会要自己用repeat画吧 ^ ^

**Comment by RubyLouvre** [comment]
我们都是repeat

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/8647486/eb41a380-298a-11e5-9ed3-4c6b746ca0d4.png)
