### ISSUE TITLE
doublelist组件中scrollbar的问题

### ISSUE THREAD

**Issue by lkiarest** [RubyLouvre/avalon.oniui#675]
我是讲doublelist放在if标签中的。当点击按钮的时候显示。
```
<div class="add modal" ms-if="showAdd">
    <div class="doublelist" ms-widget="doublelist" ms-duplex="select"></div>
</div>
```
显示的时候页面上在滚动条的拖动区域可以看到html代码
```
{{draggerHTML | html}}
```

这段代码没经过解析就显示在页面上了~~

**Comment by gogoyqj** [comment]
难道是你的avalon版本太老，未发现问题 - 顺便ms-duplux并不被支持

**Comment by lkiarest** [comment]
我把avalon和avalon都跟git代码同步了，还是有这个问题。。
我是在IE上测试的~~ 刚才试了一下火狐好像没问题。。

**Comment by gogoyqj** [comment]
@lkiarest 升级到最新的avalon确实有问题 - 在特定情形下导致doublelist依赖的scrollbar运行出错，已经在最新的oniui里修复了 - 更新srollbar的代码即可
