### ISSUE TITLE
smartgrid组件问题

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon.oniui#676]
以前用老的oniui组件，存在些很多问题，而且总感觉性能比较差，最近在产品开发中引入了新的组件，，也是遇到各种各样的问题。希望可以得到解决。
1.参数colums: {
  toggle:false
}
设置后无效，
解决：在元素id="oni-smartgrid-header"子集div上添加使用ms-visible="column.toggle"火狐下会添加display:block导致样式错误。故添加 ms-css-display="column.toggle ? 'inline-block' : 'none'"就好了。

2. 参数selectable: {
				type: "Checkbox"
			}
设置了selectable的时候 点击每列中checkbox选中背景无效
avalon.smartgrid.js 
818行 $row = avalon(target.parentNode.parentNode) -》 avalon(target.parentNode.parentNode.parentNode)

3.colums.width设置为百分比后会换算成px。不建议这样做，因大部分后台开发表格可能会自适应，故建议保留百分比。

**Comment by RubyLouvre** [comment]
建议不要使用grid
