### ISSUE TITLE
validator,norequired验证的bug

### ISSUE THREAD

**Issue by ybp825** [RubyLouvre/avalon.oniui#684]
![2345 20150727135328](https://cloud.githubusercontent.com/assets/7724264/8899421/e373ad06-3466-11e5-9aac-15499a38139c.jpg)

这几个是可以不填的，点提交还是会出现验证提示，非要输入一下，然后清空或填写正确才行。

**Comment by RubyLouvre** [comment]
这不是完整的代码啊;你要精简出一个可以调试的页面出来

**Comment by ybp825** [comment]
完整的例子我做好了，怎么给你？

**Comment by ybp825** [comment]
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
	<script type="text/javascript" src="http://cdn.bootcss.com/avalon.js/1.4.5/avalon.js"></script>
</head>
<body>
<div ms-controller="userdetail" class="ms-controller">
	<form id="userdetailForm" ms-widget="validation">
	 <div>
	 	<div style="margin-left:500px"><input type="submit" value="更新" ms-attr-disabled="isUpdate"/></div>
	 </div>
	 <div id="company-info" style="clear: left; border-top: 1px solid red;">
	 	<div style="width: 600px;float:left">
 			<label>公司邮箱：</label><input type="text" ms-duplex-norequired-email="u.company_email" data-duplex-event="change" name="company_email" /><br/><br/>
 			<label>官方QQ：</label><input type="text" ms-duplex-norequired-qq="u.official_qq" data-duplex-event="change" name="official_qq"/><br/><br/>
 			<label>官方站点：</label><input type="text" ms-duplex-norequired-url="u.site" data-duplex-event="change" name="site"/><br/><br/>
	 	</div>
	 </div>
	</form>
</div>
<script type="text/javascript">
require.config({
    //urlArgs: "v=" + (new Date - 0),
    paths: {
        jquery: "http://cdn.bootcss.com/jquery/1.11.3/jquery.js",
        mmPromise:"mmPromise",
        avalon_validation:"validation/avalon.validation"
    }
});

require(['jquery',"mmPromise",'avalon_validation','domReady!'], function($) {
	function showError(el, reason) {
        var span = $(el).next('.wran')
        if(span.length > 0){
            span.text(reason.getMessage());
        }else{
            $(el).after('<span class="wran">'+reason.getMessage()+'</span>'); 
        }
    }
    function removeError(el) {
        $(el).next('.wran').remove();
    }
    var vm = avalon.define({
        $id:"userdetail", 
        isUpdate:false,
        u:{},//作为验证的临时变量
        $skipArray: ["validation"],
        validation: {
            onReset: function(e) {
                //data.valueResetor && data.valueResetor()//清空输入框
            },
            onError: function(reasons) {
                reasons.forEach(function(reason) {
                    showError(this,reason)
                }, this)
            },
            onSuccess: function() {
                removeError(this)
            },
            onValidateAll: function(reasons) {//全部验证通过
                reasons.forEach(function(reason) {
                    showError(reason.element, reason)
                })
                if (reasons.length === 0) {
                   vm.isUpdate = true;
				   alert('ok')
                }
            }
        }
    })
	avalon.scan();
})
</script>
</body>
</html>

**Comment by roscoe054** [comment]
双工绑定的变量需要明确定义，并且赋初值。在你的例子中，可以像下面这样指定：
```html
<input ms-duplex-norequired-email="u.company_email" />
<input ms-duplex-norequired-qq="u.official_qq" />
<input ms-duplex-norequired-url="u.site" />
```
然后在定义VM时初始化它们
```javascript
var vm = avalon.define({
    $id:"userdetail",
    u:{
        company_email: "",
        official_qq: "",
        site: ""
    }
})
```

**Comment by ybp825** [comment]
谢谢楼上，原来需要明确指定属性
