### ISSUE TITLE
日历，allowBlank属性为true时，点击今天

### ISSUE THREAD

**Issue by juzhishang** [RubyLouvre/avalon.oniui#686]
allowBlank属性为true时，点击"今天"，日历面板上当前日期未被选中，只有当选中了其他日期，再次点击“今天”,才会被选中。
查看源码发先是day的值未发生改变，所以第一次点击“今天”，没有触发vmodel.$watch("day",function(){})回调~~

另外，建议增加配置项，点击“今天”可以关闭日期面板。

**Comment by roscoe054** [comment]
官网例子中你说的问题没有复现，可以给出你的使用方法吗，或者尝试升级一下你的Oni版本
