### ISSUE TITLE
对话框，当对话框中有日历控件时，可能会出现日历控件显示不完全的情况

### ISSUE THREAD

**Issue by juzhishang** [RubyLouvre/avalon.oniui#687]
问题，如题：
感觉bug在这里：

        if (targetOffsetHeight < clientHeight && targetOffsetWidth < clientWidth) {
            if (!isIE6) {
                vmodel.position = "fixed"
            }
        }

**Comment by roscoe054** [comment]
哪个浏览器下面？最好给一下你是怎么用的，然后截图看一下不完全的情况

**Comment by juzhishang** [comment]
浏览器Chrome与IE9+都测过，存在此问题。

![2015-07-29_114109](https://cloud.githubusercontent.com/assets/7800232/9031643/12c1889a-39e8-11e5-919d-5ee713080bc0.jpg)

**Comment by roscoe054** [comment]
这个问题和日历没有直接关系，只是dialog延伸出来的东西窗口放不下了。可以直接去改dialog中的样式。比如外围容器不再overflow:hidden，而出现滚动条。然后.oni-dialog设为absolute。或者去修改日历显示的位置等。
