### ISSUE TITLE
 联动的dropdown 在ie8下 会内存溢出

### ISSUE THREAD

**Issue by jeffen924** [RubyLouvre/avalon.oniui#688]
http://ued.qunar.com/oniui/index.html#avalon.dropdown.doc.html
 联动的dropdown 在ie8下 会内存溢出
请解决

**Comment by roscoe054** [comment]
请问你指的是点击前面dropdown下的选项，后面的dropdown都变成了空白吗

**Comment by jeffen924** [comment]
。。。 昨天还会 今天不会了 我更新下试试

**Comment by jeffen924** [comment]
![abe pm2qn ow0zk u20 cdv](https://cloud.githubusercontent.com/assets/13324589/8954684/dc99c452-3619-11e5-8e7e-2008f86158b8.png)


但我更新了之后还是这样

**Comment by roscoe054** [comment]
这个问题应该是调用层级太高的原因，在IE下就会报这个警告。后面会对该组件进行优化。

**Comment by jeffen924** [comment]
那我当前应该怎么解决这个问题？ 或者避免这个问题？



施杰锋（steven） 
奥林网络科技（宁波）有限公司
电话：0574-88445656-816
邮件：jiefengsh@olymtech.com
网址：www.olymtech.com www.500jit.com www.800jit.com
地址：宁波市鄞州区日丽中路555号（华茂总部壹号1907室）
邮编：315100
热线：400-882-8871 【试灵灵，帮帮你，帮帮企业】
 
发件人： Yuhao Ju
发送时间： 2015-07-29 19:49
收件人： RubyLouvre/avalon.oniui
抄送： jeffen924
主题： Re: [avalon.oniui] 联动的dropdown 在ie8下 会内存溢出 (#688)
这个问题应该是调用层级太高的原因，在IE下就会报这个警告。后面会对该组件进行优化。

**Comment by roscoe054** [comment]
最快的解决方式是采用setTimeout(function, 0)清除调用栈，将例子中onChange调用里面的代码修改一下：

```javascript
 $areaOpts: {
    onChange: function(n) {
        var area = dropdown.places[avalon(this).data("index")];

        setTimeout(function(){
            area.provinces.clear();
            area.provinces.pushArray(provincesMap[n]);
            area.province = area.provinces[0];
        }, 0)
    }
},
$provinceOpts: {
    onChange: function(n) {
        var area = dropdown.places[avalon(this).data("index")];

        setTimeout(function(){
            area.cities.clear();
            area.cities.pushArray(citiesMap[n]);
            area.city = area.cities[0];
        }, 0)

    }
}
```

**Comment by gogoyqj** [comment]
The quick summary is: recursion that passes through the host global object is limited to a stack depth of 13. In other words, if the reference your function call is using (not necessarily the function itself) was defined with some form window.foo = function, then recursing through foo is limited to a depth of 13.

**Comment by gogoyqj** [comment]
@jeffen924  这个可以多给点信息不

**Comment by gogoyqj** [comment]
fixed
