### ISSUE TITLE
resizable的等比缩放功能不能用啊

### ISSUE THREAD

**Issue by wf123537200** [RubyLouvre/avalon.oniui#690]
在项目中要用到等比缩放，发现除了右下角和右，下边可以等比缩放以外，其他角和边都没有办法保证比例不变。在oniui官网的例子里面就可以看到效果。

http://hotelued.qunar.com/oniui/resizable/avalon.resizable.ex3.html

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon.oniui/pull/691 已修
