### ISSUE TITLE
pager组件有个问题

### ISSUE THREAD

**Issue by yutent** [RubyLouvre/avalon.oniui#696]
在用 ms-include-src="tpl" 载入一个包含 ms-widget="pager, xxoo”时， 如果来回切换 tpl ，则会报warning: xxoo 已经存在于avalon.vmodels中。 如果不指定xxoo，如ms-widget="pager”，那样就不会报这个warning。

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/issues/959 与这问题一样
