### ISSUE TITLE
请问下如何将oniui发布到CDN上呢？

### ISSUE THREAD

**Issue by lkiarest** [RubyLouvre/avalon.oniui#702]
使用requirejs引入oniui，在开发环境都好的，请问有将oniui部署到CDN上面的方案吗？
非常感谢~~

**Comment by RubyLouvre** [comment]
这问后端啊，建议还是要打包

**Comment by lkiarest** [comment]
@RubyLouvre 是的，不打包的话直接放目录到CDN服务器报各种错。。 估计要打一个all.js
