### ISSUE TITLE
avalon.pager的页码问题

### ISSUE THREAD

**Issue by liminghui** [RubyLouvre/avalon.oniui#710]
avalon.pager.html这个页面
13行和24行 ms-class-oni-state-active="currentPage == 1"
应改为ms-class="oni-state-active:currentPage == 1"
不然在avalon1.4.6版本上，class会添加不上

**Comment by RubyLouvre** [comment]
升到1.4.6.1 
```
  binding.expr = '[' + quote(oldStyle) + "," + binding.expr + "]"
```
-->
```
  binding.expr = '[' + quote(oldStyle) + "," + true + "]"
```
