### ISSUE TITLE
smartgrid渲染空值问题

### ISSUE THREAD

**Issue by lkiarest** [RubyLouvre/avalon.oniui#713]
使用smartgrid的示例页面avalon.smartgrid.ex1.html，如果将data数组中name的值设为null对象，在页面上渲染之后显示的是字符串"null"，后面如果从data里取值取到的也是字符串"null"。
调试的时候可以看到拼html的时候是直接用 "+" 将format之后的cellValue 加到html字符串的，没有判断是否为null，应该是这个原因导致的。

**Comment by roscoe054** [comment]
我这里从data里取出来的不是字符串的，可以看看你这块的代码吗？
```javascript
function getDatas(number) {
    var data = []
    for (var i = 0; i < number; i++) {
        data.push({
            name: null,
            age: parseInt(10 + Math.random() * 20),
            selected: i%3 ? false: true,
            salary: parseInt(Math.random() * 100),
            operate : i % 5 ? 0 : 1,
            busy : !i%3 && !i%5 ? 0 : 1
        })
    }
    return data
} 
```
![image](https://cloud.githubusercontent.com/assets/4938243/9321402/76e38236-4598-11e5-8198-29733eb5f6ca.png)

**Comment by lkiarest** [comment]
噢，可能取的时候从vm获取了。显示的时候有问题。。
