### ISSUE TITLE
scrollbar组件问题

### ISSUE THREAD

**Issue by Mr-Yy** [RubyLouvre/avalon.oniui#716]
我在做一个需要滚动加载分页的列表。结构大致是这样的：
    
    <ul ms-controller='test'>
        <li class="item" ms-widget="scrollbar"><p></p></li>
        <li class="item" ms-widget="scrollbar"><p></p></li>
        <li class="item" ms-widget="scrollbar"><p></p></li>
        <li class="item" ms-widget="scrollbar"><p></p></li>
    </ul>

列表的数据都是通过ajax请求出来的，包括第一页的数据。多余数据需要滚动加载，每一个item里面都有一个scrollbar的组件。
现在遇到的问题是在第一次刷新页面时，进行了一次avalon.scan()。第一页的Item里面的scrollbar都生效了。但是当加载到第二页的时候，新生成的item里面的scrollbar没有扫描到。想问一下怎么样才能实现这个功能。

**Comment by gogoyqj** [comment]
加载完之后，avalon.scan(ul)一次

**Comment by Mr-Yy** [comment]
第二次扫描没有成功。扫描不到新生成的item

**Comment by Mr-Yy** [comment]
目前解决的办法是每一次加载的数据生成一个新的vm。不知道还有没有别的办法。

**Comment by gogoyqj** [comment]
avalon.scan(ul, [avalon.vmodels.test])
