### ISSUE TITLE
打包后fileuploader组件造成字体冲突问题

### ISSUE THREAD

**Issue by lkiarest** [RubyLouvre/avalon.oniui#719]
使用rjs和text,css插件打包的时候如果将fileuploader一起打包压缩包里，会造成其他组件（比如对话框，日期选择）图标显示不对（关闭对话框变成了信封）。
应该是由于在fileuploader的css中定义了跟oniui-common.css中同样的字体名称，但是引入的字体文件并不一样。
一个是：http://source.qunarzz.com/fonts/oniui/0.0.3/oniui-webfont.eot?#iefix&v=4.2.0
另一个是：http://simg4.qunarzz.com/fonts/fontawesome/4.2.0/fontawesome-webfont.eot?#iefix&v=4.2.0
将fileuploader组件中定义的字体名称改一个就可以了

补充： fileuploader中也定义了同样了class名：.oni-icon，这个东东也要改掉

**Comment by roscoe054** [comment]
@lkiarest 谢谢指出，已修复
