### ISSUE TITLE
datepicker组件的bug，我自己暂时已修复，麻烦看看

### ISSUE THREAD

**Issue by liminghui** [RubyLouvre/avalon.oniui#720]
#### 原代码为
	if ((dayNames.indexOf(dayName) % 7 == 0) || (dayNames.indexOf(dayName) % 7 == 6)) {
		return "oni-datepicker-week-end"
	} else {
	    return ""
	}
#### 修改为
	if (dayNames) {
        if ((dayNames.indexOf(dayName) % 7 == 0) || (dayNames.indexOf(dayName) % 7 == 6)) {
            return "oni-datepicker-week-end"
        } else {
            return ""
        }
    }

#### 原版本会报下面的警告
	warning:exception throwed in [avalon.injectBinding]  TypeError: Cannot read property 'indexOf' of undefined

#### 原代码为
	options.currentOption = dataModel[i];
#### 修改为
	options.currentOption = avalon.mix(true, {}, dataModel[i]);

#### 原版本会报下面的错误
	Uncaught TypeError: Cannot read property '$events' of null
	accessor @ avalon.js:1340
	(anonymous function) @ avalon.dropdown.js:185
	callback @ avalon.js:131
	
这是由于“使日历可以通过下拉框切换月份和年份的显示”这个例子当我们的月份是8月份的时候，我们在<code>avalon.dropdown.js，73行的options.currentOption = dataModel[i];</code>获取的是一个引用，当点击next箭头选取下一个月份的时候在<code>avalon.dropdown.js，185行的vmodel.currentOption = setLabelTitle(n);</code>赋值时会覆盖引用数组的值，从而导致在下面的方法出错

	function setLabelTitle(value) {
	    var option = vmodel.data.$model.filter(function(item) {
	        return item.value === value;
	    });
	
	    option = option.length > 0 ? option[0] : null
	
	    if(!option && vmodel.data.length) {
	        avalon.log("[log] avalon.dropdown 设置label出错");
	    } else if (option) {
	        vmodel.label = option.label;
	        vmodel.title = option.title || option.label || "";
	    }
	
	    return option;
	}

### 以上是我暂时的解决方法

**Comment by lkiarest** [comment]
貌似这个问题也会造成内存泄漏

**Comment by RubyLouvre** [comment]
good，我让人跟进一下

**Comment by lkiarest** [comment]
改过之后也有内存泄漏，应该是这个控件销毁的时候有问题。。

**Comment by roscoe054** [comment]
@lkiarest 你是怎么操作这个控件的，内存泄漏了多少？

**Comment by liminghui** [comment]
意思是还有这个控件的引用保留在页面吗

**Comment by lkiarest** [comment]
是的，我加上这个控件后，用mmstate来回切换页面内存会一直增长很快

**Comment by roscoe054** [comment]
@liminghui 已修复

**Comment by roscoe054** [comment]
@lkiarest 我用mmstate和dropdown一起测试，发现没有明显的内存泄露，也可能是页面的其它原因导致的？

**Comment by lkiarest** [comment]
@roscoe054 额，不好意思，我是用的datapicker控件~~ 好像不会被销毁

**Comment by gogoyqj** [comment]
1，里边的事件绑定没有回收 - 这是一个方面

**Comment by gogoyqj** [comment]
这个问题比较棘手，波及面挺广的 - 和dom节点关联的地方

**Comment by lkiarest** [comment]
@gogoyqj hi, 我模仿其他组件的写法写了一个简单的表格组件，不过在mmstate里切换页面的时候还是会出现内存泄漏，可以麻烦你帮我看下写法有什么问题么？~~ 
地址在： https://github.com/lkiarest/oniui-extend/tree/master/hygrid

**Comment by gogoyqj** [comment]
沒有回收邏輯，$remove

**Comment by lkiarest** [comment]
@gogoyqj 我在$remove里面把节点清空了：vm.widgetElement.innerHTML = "";，我看其他组件也是这样处理的，还有其他地方需要释放的吗~

**Comment by gogoyqj** [comment]
事件解綁，解除 widget vmodel和元素的相互引用
