### ISSUE TITLE
datepicker组件的bug，遮罩的问题

### ISSUE THREAD

**Issue by liminghui** [RubyLouvre/avalon.oniui#721]
![123123](https://cloud.githubusercontent.com/assets/10808093/9426887/e71ea5a8-498f-11e5-8610-b3960f74f169.jpg)

***
## 我暂时的解决方法是将<code>z-Index</code>取消了
***

![image](https://cloud.githubusercontent.com/assets/10808093/9426892/15cd6736-4990-11e5-8c9f-428fc6819bf1.png)

**Comment by roscoe054** [comment]
这个是可以根据业务场景自己来调整的，因为不可能适应所有的情况。。。
