### ISSUE TITLE
fileuploader 可不可以改变上传展示的样式

### ISSUE THREAD

**Issue by xingxiulaoxian** [RubyLouvre/avalon.oniui#738]
现在开发的页面和fileuploader的风格有很大的差异，就想改下风格，但是改了之后ie兼容就很不好了

**Comment by xuzicn** [comment]
事实上你只要改css或者模板就好了。兼容问题，主要发生在IE6-9上吧？如果是改完CSS后点击按钮没有弹文件选择窗口出来，那么9成是Flash没有覆盖在上传按钮上，还是要在CSS上下工夫了。

**Comment by xuzicn** [comment]
github墙了，很不方便。这个组件的问题请上http://www.avalon.org.cn交流
