### ISSUE TITLE
mmstate dialoig能不能改一版dialog支持mmstate的啊。

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon.oniui#745]
两个视图切换 dialog中又引用的同一个页面，此页面中使用了id。就会报错。
而且如果不设置data-dialog-container将dialog视图设置在controller中的话body下会无限增长元素

**Comment by gogoyqj** [comment]
这种，你应该直接在body下弄一些元素专门来放dialog

**Comment by lkiarest** [comment]
我自己模仿着写了dialog组件~~
