### ISSUE TITLE
怎么才能知道fileupload是否上传结束了

### ISSUE THREAD

**Issue by xingxiulaoxian** [RubyLouvre/avalon.oniui#747]
虽然知道返回值在哪里但是不知道什么时候去取。。

**Comment by xuzicn** [comment]
问的好。这个地方的文档我没写完整。
vm的onFileRequestResponsed回调包含三个参数，fileObj、textStatus和responseText，其中fileObj.status包含了文件的状态，说明如下：
	fileObj.FILE_INIT = 0;	// 文件被加入后的原始状态，即文件选中后时的状态代码，这个状态非常短暂。
	fileObj.FILE_CACHED = 1; // 已被runtime缓存。当你看到文件的缩略的时候已经变成了这个状态
	fileObj.FILE_QUEUED = 2; // 已进入发送队列。点击上传的时候，会立即进入发送队列，此时状态代码是FILE_QUEUED
	fileObj.FILE_IN_UPLOADING = 5; // 文件已经开始上传。排队结束，第一个分块已经开始发送。
	fileObj.FILE_UPLOADED = 6; // 文件上传结束。
	fileObj.FILE_ERROR_FAIL_READ = 101; // FileQueue无法读取文件。读取文件错误
	fileObj.FILE_ERROR_FAIL_UPLOAD = 103; // FileQueue发送文件时碰见错误，包含网络错误等。

文档稍后补齐。

**Comment by xuzicn** [comment]
具体的实现就是在
vm.options.onFileRequestResponsed = function (fileObj, textStatus, responseText) {
     if (fileObj.status === fileObj.FILE_UPLOADED) {
         // Something to do
     }
}
