### ISSUE TITLE
fileuploader没有对外提供删除预览的功能吗？

### ISSUE THREAD

**Issue by codering** [RubyLouvre/avalon.oniui#761]
是这样的，我在一个dialog组件里，用fileuploader组件选择了一个文件。当这个dialog关闭再打开，这个预览文件还在，我现在自己处理的方式是
![image](https://cloud.githubusercontent.com/assets/2271825/10013008/117d9f4e-6140-11e5-96f8-4d646d8870e9.png)

希望上传组件自身能提供方法，重置上传组件。

**Comment by xuzicn** [comment]
先记下，慢慢改

**Comment by codering** [comment]
文件上传，难用的要死啊。。。。。。其实整个oniui都不咋样，各种坑，用户完全就是小白鼠！

**Comment by lkiarest** [comment]
@codering 我们基本都是自定义或者用第三方的。。

**Comment by codering** [comment]
@lkiarest 你们现在都自己写了哪些组件？

**Comment by RubyLouvre** [comment]
看来大家都对oniui不满，我启动一个新项目吧，基于bootstrap进行二次开发
