### ISSUE TITLE
写在ms-repeat里面的ms-duplex-xxx没有被validation组件扫描到

### ISSUE THREAD

**Issue by wonderbeyond** [RubyLouvre/avalon.oniui#770]
```html
<div ms-controller="main">
    <form ms-widget="validation">
        <div ms-repeat="purchaseItems">
            <input ms-duplex-decimal="el.money" />
        </div>
    </form>
</div>
```

如上的代码结构，ms-duplex-decimal由于写在了ms-repeat中，并没被validation扫描到，导致是Avalon自身去调用decimal的duplext hook。

根据调试发现，是avalon内部的pipe方法去调用validation组件往avalon.duplexHooks中注入的decimal方法，但是avalon的内部调用不满足被注入的函数签名，缺少next参数。

相关代码:

- avalon内部调用duplexHooks: https://github.com/RubyLouvre/avalon/blob/master/avalon.js#L3745
- validation组件调用duplexHooks: https://github.com/RubyLouvre/avalon.oniui/blob/master/validation/avalon.validation.js#L586

备注:

- avalon 版本: 1.4.5
- oniui.validation 版本: 未知(看不出来)

**Comment by RubyLouvre** [comment]
已经修复
