### ISSUE TITLE
[avalon.validation]如何实现单纯的输入警告逻辑

### ISSUE THREAD

**Issue by wonderbeyond** [RubyLouvre/avalon.oniui#773]
除了输入错误需要提示并阻止提交之外，我觉得单纯的警告也是有必要的。

比如“购买金额”字段，后台只能接受两位小数的数字，但是我们不想阻止用户输入超过两位小数的数值，而是想仅仅做这样一个提示：“注意，您输入的金额将被四舍五入到小数点后两位！”

请问，如何实现呢，或者能否考虑提供支持呢？

---

我目前仅仅是覆盖了`avalon.validation`附带的`decimal`来阻止用户输入大于指定小数位数的数值：

```javascript
            validation: {
                validationHooks: {
                    decimal: {
                        message: '{{message}}',
                        get: function(value, data, next) {
                            var elem = data.element;
                            var maxDecimalPlaces = elem.getAttribute('data-duplex-max-decimal-places');
                            data.data.maxDecimalPlaces = maxDecimalPlaces;
                            next(new RegExp('^\\-?\\d*(\\.\\d{0,' + maxDecimalPlaces + '})?$').test(value));
                            return value;
                        }
                    },
                    // ...
```

**Comment by wonderbeyond** [comment]
我觉的可以在执调用`hook`是传递的参数中，多加一个`notify`的回调，校验函数可以按需传递消息。

avalon.validation代码中值得注意地方: https://github.com/RubyLouvre/avalon.oniui/blob/master/validation/avalon.validation.js#L586

修改建议：
![22f](https://cloud.githubusercontent.com/assets/228361/10726413/89051f3c-7c0d-11e5-93a6-9abf2ae0ffee.png)

**Comment by RubyLouvre** [comment]
这也可以在next中处理啊

**Comment by wonderbeyond** [comment]
@RubyLouvre 
现在的情况是给next传递的值, 只做了布尔真假判断.
在next内部, 为真, 就resolve(true), 否则就resolve(object), 后面 Promise.all 只要看到有对象值就认为校验失败了.

---

next目前把参数当bool值, 恐怕不好扩展吧.

**Comment by RubyLouvre** [comment]
这个好难改。。。

**Comment by wonderbeyond** [comment]
那且看业务需要喽，我们是有这需要，但是不好实现也就理解了😀
