### ISSUE TITLE
报错：懒加载组件

### ISSUE THREAD

**Issue by niuniu384665340** [RubyLouvre/avalon.oniui#783]
懒加载组件在组件库案例中正常，avalon.js换成1.5.4版本运行图片没有渲染出来，没有报错！

**Comment by roscoe054** [comment]
avalon.js 1.5版本以上，不支持ms-widget方式定义组件，所以avalon.oniui在1.5以上版本中用不了，只能切换成低版本avalon运行

**Comment by niuniu384665340** [comment]
请问，oniui是否有计划升级支持avalonjs1.5版本？

**Comment by RubyLouvre** [comment]
不计划;不过会将大部分组件迁移到avalon.bootstrap中
