### ISSUE TITLE
IE8下doublelist组件滚动条拖不动

### ISSUE THREAD

**Issue by soulkiller** [RubyLouvre/avalon.oniui#792]
doublelist中条目过多出现滚动条后，鼠标拖动滚动条的时候列表在动，但是右侧的滚动条不滚动。官方demo页面也有此现象
http://ued.qunar.com/oniui/index.html#!/widgets?widgetId=doublelist
建议不使用scrollbar控件

**Comment by gogoyqj** [comment]
。。。跟数据没有关系，是scrollbar的样式加载进来晚了，这个合并代码之后，以及确保样式已经加载了，都不会出现这个问题

**Comment by lkiarest** [comment]
官方页面确实有问题~~

**Comment by RubyLouvre** [comment]
打包后就好了

**Comment by soulkiller** [comment]
@RubyLouvre 用requirejs打包后还是有同样的问题

**Comment by gogoyqj** [comment]
@soulkiller 你发个可以看的地址来

**Comment by lkiarest** [comment]
是IE8下面的opacity属性问题造成的，scrollbar的背景很多地方调用的
```
css("opacity", 1)
```
在IE8下这种元素上面的鼠标事件会有bug，测试的时候去掉这个属性设置就好了，估计要考虑这个属性的兼容性实现~~

**Comment by gogoyqj** [comment]
好吧，我屏蔽掉低端浏览器

**Comment by gogoyqj** [comment]
好吧，我屏蔽掉低端浏览器

**Comment by gogoyqj** [comment]
好吧，我屏蔽掉低端浏览器

**Comment by gogoyqj** [comment]
目测已经修复了
