### ISSUE TITLE
求助，单例无法运行！是不是oniui版本问题？

### ISSUE THREAD

**Issue by csdudu** [RubyLouvre/avalon.oniui#801]
我现在用
avalon.mobile.js 1.5.6 built in 2015.12.1
oniui是我从这里刚下载的，应该是最新版本，版本显示是avalon 1.3.6 spinner。主要代码如下：
<body ms-controller="demo">
<h1>aaa={{aaa}}</h1>
<script src="js/avalon.mobile.js"></script>
<script>
require(["oniui/spinner/avalon.spinner"], function(avalon) {
	console.log("done!");
    var vm = avalon.define({ 
    $id: "demo", 
    aaa:123
	 }) 
})
</script>
路径应该无误，因为能看到测试器成功加载依赖文件，但正文无法运行.求解！

![qq 20151228102454](https://cloud.githubusercontent.com/assets/5706088/12013238/458c4ab6-ad4d-11e5-85c7-3baa715553fc.png)

**Comment by RubyLouvre** [comment]
1.5.*不支持oniui， 官网已经写得清清楚楚！
