### ISSUE TITLE
datepicker允许选择年份月份时的问题

### ISSUE THREAD

**Issue by supersoup** [RubyLouvre/avalon.oniui#821]
avalon 1.4.6版本：
一、首次点击后日历界面无法对应当前时间
日历选择器，使用年份月份下拉框选择，目前github上的版本点开之后，当前显示的日历没有对应上vm，也没有对应到今天的日期，而是设置最小的日期：
![image](https://cloud.githubusercontent.com/assets/16763278/16400925/590e5d04-3d12-11e6-9a05-9f8e31393b6d.png)

然后重新点击一次后，才能够对应到vm里的日期：
![image](https://cloud.githubusercontent.com/assets/16763278/16401214/59c268aa-3d15-11e6-8bc8-92b8035fbcb5.png)

所有浏览器都存在这个问题，oniui版本是github上最新的版本。但是oniui官方文档的演示里面不存在这个问题。

二、日历插件里的下拉框上下箭头，点击虽然能够让下拉框移动，但是，松开鼠标后会导致datepicker关闭：
![image](https://cloud.githubusercontent.com/assets/16763278/16401268/fa32f354-3d15-11e6-844b-73bb1e7c0b17.png)

**Comment by roscoe054** [comment]
第一个问题github上的版本我试了最新的，没有复现，是可以对应到今天日期的。我猜可能是你使用的时候绑定了ms-duplex，而这个值不是今天？

第二个问题和松开时候的焦点有关，如果焦点移出了滚动条datepicker就会关闭。这个和滚动条组件可能也有关，我跟进看看能不能fix。

**Comment by supersoup** [comment]
可是我刚才才git clone的oniui，然后打开avalon.oniui/datepicker/avalon.datepicker.ex7.html试了一下：

![image](https://cloud.githubusercontent.com/assets/16763278/16407976/0a375690-3d49-11e6-9be9-5f55c2a357b0.png)

第一次点开的时候，我本机的确实没有对应到今天。第二次点开，或者输入空格或其他字符，才能够跳到当前的值上面。
您再试试看看呢？

**Comment by roscoe054** [comment]
@supersoup 已提pr  #823
