### ISSUE TITLE
oniui的fileuploader上传文件报Fail to upload file

### ISSUE THREAD

**Issue by supersoup** [RubyLouvre/avalon.oniui#822]
上传一个文件，大约有8m的样子，然后出现如下错误：（小文件上传是没有问题的）

但是我的代码中配置了文件的大小的：
![image](https://cloud.githubusercontent.com/assets/16763278/16448372/b5ce169e-3e23-11e6-887a-c9d154e25b2b.png)

html部分：
`<div ms-widget="fileuploader, $, $uploader"></div>`

js部分：
`$uploader: {
            maxFileSize: 20485760,
            filePoolSize: 204857600,
            addButtonText: "添加文件",
            uploadButtonText: "上传文件",
            previewWidth: 360,
            previewHeight: 50,
            acceptFileTypes: "*",
            showProgress: true,
            enableDragDrop: true,
            serverConfig: {
                url: "/PyPlatformConsole/add_report_file.action"
            },
            onFileOverSize: function (fileObj) {
                alert(fileObj.name+"超出了文件尺寸限制")
            },
            onFilePoolOverSize: function (fileObj, poolSize) {
                alert("文件缓存池达已满，不能继续添加文件。")
            },
            onSameFileAdded: function () {
                alert("不能添加相同的文件");
            }
        },`

然后查看chrome的network里面，发现，我的请求并没有发出去：
![image](https://cloud.githubusercontent.com/assets/16763278/16448394/d0b8292c-3e23-11e6-9d3b-6ac59bc342f2.png)

请教这是什么问题呢？万分感谢！！！

**Comment by xuzicn** [comment]
请求发出去了啊，服务器那边接收文件的代码没做好吧？从截图看，文件被分成了两块，你的服务是不是不支持分块上传呢？

**Comment by supersoup** [comment]
恩，是的，没有做分块上传。现在改好了，是服务器那边的问题。谢谢。
